# Generated by Django 5.0.6 on 2024-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerdocument',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
