# Generated by Django 5.0.6 on 2024-07-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_officerdocument_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
    ]
